// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCnNrIz2g2Ovq5XnocJVBVl5S065vOB2g',
    appId: '1:4824580226:web:e28624a19f13361241f49b',
    messagingSenderId: '4824580226',
    projectId: 'icteach-free',
    authDomain: 'icteach-free.firebaseapp.com',
    storageBucket: 'icteach-free.firebasestorage.app',
    measurementId: 'G-S77WYVMF0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-pADzXbDBOOYZGEX0cwPXJaXZOw3T19E',
    appId: '1:4824580226:android:a8e7dfaeb48c02f741f49b',
    messagingSenderId: '4824580226',
    projectId: 'icteach-free',
    storageBucket: 'icteach-free.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnuCRAhEyZ4ntNBAa1ybYQnpHgCJqnhOE',
    appId: '1:4824580226:ios:75985b00acc5b26a41f49b',
    messagingSenderId: '4824580226',
    projectId: 'icteach-free',
    storageBucket: 'icteach-free.firebasestorage.app',
    iosBundleId: 'com.example.icteach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnuCRAhEyZ4ntNBAa1ybYQnpHgCJqnhOE',
    appId: '1:4824580226:ios:75985b00acc5b26a41f49b',
    messagingSenderId: '4824580226',
    projectId: 'icteach-free',
    storageBucket: 'icteach-free.firebasestorage.app',
    iosBundleId: 'com.example.icteach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCnNrIz2g2Ovq5XnocJVBVl5S065vOB2g',
    appId: '1:4824580226:web:8ff0c068b6e8dec841f49b',
    messagingSenderId: '4824580226',
    projectId: 'icteach-free',
    authDomain: 'icteach-free.firebaseapp.com',
    storageBucket: 'icteach-free.firebasestorage.app',
    measurementId: 'G-8J60G2FEZJ',
  );

}